### ISSUE TITLE
requirements_base.txt missing in the package

### ISSUE THREAD

**Issue by cheolgook** [PythonicNinja/pydrill#29]
We're running into this issue with installing pydrill:

```
Downloading/unpacking pydrill (from -r /home/jenkins/workspace/platform-tools/requirements.txt (line 20))
  Downloading pydrill-0.3.1.tar.gz
  Running setup.py egg_info for package pydrill
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/jenkins/workspace/platform-tools/virtualenv/build/pydrill/setup.py", line 17, in <module>
        requirements = open('requirements_base.txt', 'r').readlines()
    IOError: [Errno 2] No such file or directory: 'requirements_base.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/jenkins/workspace/platform-tools/virtualenv/build/pydrill/setup.py", line 17, in <module>

    requirements = open('requirements_base.txt', 'r').readlines()

IOError: [Errno 2] No such file or directory: 'requirements_base.txt'
```

and it seems like the package is missing requirements_base.txt file?

**Comment by asettouf** [comment]
There are at least 2 ways listed in the README.rst to install pydrill, could you elaborate on how you do it?

**Comment by PythonicNinja** [comment]
Hello @asettouf!

Here I provide a list of commands which will allow you to use pydrill:
```
|  ~/PycharmProjects   (master)
| => mkdir checking-pydrill
 20:41:23 ________________________________________________________________________________
| pythonicninja
|  ~/PycharmProjects   (master)
| => cd checking-pydrill/
 20:41:27 ________________________________________________________________________________
| pythonicninja
|  ~/PycharmProjects/checking-pydrill   (master)
| => virtualenv env -p python3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/pythonicninja/PycharmProjects/checking-pydrill/env/bin/python3.5
Also creating executable in /Users/pythonicninja/PycharmProjects/checking-pydrill/env/bin/python
Installing setuptools, pip, wheel...done.
 20:41:38 ________________________________________________________________________________
| pythonicninja
|  ~/PycharmProjects/checking-pydrill   (master)
| => e
(env)  20:41:40 ________________________________________________________________________________
| pythonicninja
|  ~/PycharmProjects/checking-pydrill   (master)
| => pip install pydrill
Collecting pydrill
  Downloading pydrill-0.3.1-py2.py3-none-any.whl
Collecting requests (from pydrill)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->pydrill)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->pydrill)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->pydrill)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->pydrill)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Installing collected packages: idna, chardet, certifi, urllib3, requests, pydrill
Successfully installed certifi-2017.11.5 chardet-3.0.4 idna-2.6 pydrill-0.3.1 requests-2.18.4 urllib3-1.22
(env)  20:41:46 ________________________________________________________________________________
| pythonicninja
|  ~/PycharmProjects/checking-pydrill   (master)
| => python
Python 3.5.2 (default, Sep  3 2016, 18:26:30)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydrill
>>>
```

**Comment by asettouf** [comment]
Hello @PythonicNinja 

My fault, I wanted the OP, @cheolgook,  to give the exact steps to reproduce the issue, I believe the README.rst is pretty clear on the procedure though.

**Comment by pkennedy89** [comment]
Hi @asettouf,

I'm coming across the same issue when I try to install pydrill using pip as specified in the README.rst:
`pip install pydrill`

I get the following error:

**Comment by PythonicNinja** [comment]
solved the issue with new release

https://github.com/PythonicNinja/pydrill/releases/tag/v0.3.3

**Comment by PythonicNinja** [comment]
@pkennedy89 Hope it solved your problem.
